#!/bin/bash
if [[ $BASH_SOURCE = */* ]]; then
    mccdir=${BASH_SOURCE%/*}/
else
    mccdir=./
fi

java -Djava.util.logging.config.file=logging.properties --enable-preview -cp "${mccdir}target/classes" com.quaxt.mcc.Mcc "$@"
